[build]
base = "Frontend"  # Go inside the Frontend directory
command = "npm install && npm run build"
publish = "Frontend/build"  # Make sure this is correct

[[redirects]]
from="/*"
to="/index.html"
status= 200

