[build]
base = "shihab"  # Go inside the Frontend directory
command = "npm install && npm run build"
publish = "build"  # Make sure this is correct

[[redirects]]
from="/*"
to="/index.html"
status= 200

